# Generated by Django 4.1.7 on 2023-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(auto_created=True, default='file_from_2023-03-17 19:42:32.736043', max_length=100),
        ),
    ]
