# Generated by Django 4.1.7 on 2023-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_file_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='quants/Notion_DB/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
