# Generated by Django 4.1.7 on 2023-03-17 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_file_file_alter_file_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
