from dotenv import load_dotenv
from bot import Bot
import pandas as pd

def test(number_of_questions = 10, hardmode = False,  env_loaded = True):
    """
    This function generates a questionnaire based on the TruthfulQA dataset with a specified number of questions and difficulty level. The output of the questionnaire, 
    as answered by a Bot, is saved in a .csv file. The intention of this function is to prepare questions_input.csv to be used for evalute.py.

    ## Parameters:

    - number_of_questions (int, optional): The number of questions to generate in the questionnaire. Default is 10.
    - hardmode (bool, optional): If True, the questionnaire will include correct and incorrect answers. Default is False.
    - env_loaded (bool, optional): If True, the function assumes that the environment variables have already been loaded. If False, the function loads the environment variables. Default is True.

    ## Output:

    - A .csv file containing the generated questionnaire with the following columns:
        - Question: The question text.
        - Answer: The correct answer to the question.
        - HNTG: The response generated by the Bot based on the question text.
    """

    if not env_loaded:
        load_dotenv()

    df = pd.read_csv("TruthfulQA/TruthfulQA.csv")
    reshuffle = df.sample(n=number_of_questions).reset_index(drop=True)

    with open("TruthfulQA/AnswerSheet.txt", 'w') as answer_sheet:
        for index, row in reshuffle.iterrows():
            answer_sheet.write(row['Best Answer'] + ". ")

            if hardmode:
                answer_sheet.write(row['Correct Answers'] + ". ")
                answer_sheet.write(row['Incorrect Answers'] + ". ")

    b = Bot("TruthfulQA/AnswerSheet.txt")

    reshuffle['HNTG'] = reshuffle['Question'].apply(lambda question: " " + b.query(question))

    reshuffle.to_csv('TruthfulQA/questions_input.csv')

test(2)
